RandomFilms/Controllers/FilmController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RandomFilms.Data;
using RandomFilms.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RandomFilms.Controllers
{
    [ResponseCache(Duration = 2678400, Location = ResponseCacheLocation.Client)]
    public class FilmController : Controller
    {
        private readonly ILogger<FilmController> _logger;
        static Random random = new Random();
        DataManager data;
        public FilmController(DataManager _data, ILogger<FilmController> logger)
        {
            data = _data;
            _logger = logger;
        }
        [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
        [HttpGet]
        [Route("film/")]
        public IActionResult Index()
        {
            try
            {
                var model = data.Films.GetFilmByFilmId(new Random().Next(1, (data.Films.AllFilms().Count() + 1)));
                if (model == null)
                {
                    return NotFound();
                }
                return RedirectToAction("Index", new { id = model.Id });
            }
            catch (Exception ex)
            {
                _logger.LogError($"[{DateTime.Now}]\nError: {ex.Message}");
                return NotFound();
            }

        }

        [HttpGet]
        [Route("film/{id}")]
        public IActionResult Index(int id)
        {
            try
            {
                var model = data.Films.GetFilmById(id);
                if (model != null)
                {
                    FilmModelView view = new FilmModelView
                    {
                        Film = model,
                        State = 0
                    };
                    return View(view);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"[{DateTime.Now}]\nError: {ex.Message}");
                return NotFound();

            }
        }
        [HttpGet]
        public IActionResult Index(FilmModelView view)
        {
            if (view.State == 1)
            {
                view.Film = data.Films.GetFilmByFilmId(new Random().Next(1, (data.Films.AllFilms().Count() + 1)));
            }
            return View(view);
        }
        [HttpPost]
        public IActionResult Index(SelectedCategoriesModel model)
        {
            try
            {
                List<GenreModel> allgeners = data.Generes.AllGenres().ToList();
                List<FilmGenersModel> generIn = new List<FilmGenersModel>();
                List<FilmGenersModel> generOut = new List<FilmGenersModel>();
                List<FilmModel> sorted = new List<FilmModel>();
                if (model.GenreIn != null || model.GenreOut != null)
                {
                    if (model.GenreIn != null)
                    {
                        for (int i = 0; i < model.GenreIn.Length; i++)
                        {
                            FilmGenersModel gener = new FilmGenersModel
                            {
                                Id = i,
                                Gener = allgeners.Find(x => x.Id.Equals(model.GenreIn[i])).Genre
                            };
                            generIn.Add(gener);
                        }
                    }
                    if (model.GenreOut != null)
                    {
                        for (int i = 0; i < model.GenreOut.Length; i++)
                        {
                            FilmGenersModel gener = new FilmGenersModel
                            {
                                Id = i,
                                Gener = allgeners.Find(x => x.Id.Equals(model.GenreOut[i])).Genre
                            };
                            generOut.Add(gener);
                        }
                    }
                    if (generIn.Count > 0 && generOut.Count > 0)
                    {
                        sorted = data.Films.GetSelectedGeners(generIn, generOut).ToList();
                    }
                    else if (generIn.Count > 0 && generOut.Count == 0)
                    {
                        sorted = data.Films.GetSelectedGenersIn(generIn).ToList();
                    }
                    else if (generIn.Count == 0 && generOut.Count > 0)
                    {
                        sorted = data.Films.GetSelectedGenersOut(generOut).ToList();
                    }
                    if (sorted.Count == 0)
                    {
                        return Index(new FilmModelView { State = 1 });
                    }
                    int index = random.Next(sorted.Count);
                    var filmmodel = data.Films.GetFilmById(sorted[index].Id);
                    GC.Collect();

                    return RedirectToAction("Index", new { id = filmmodel.Id });
                }
                else
                {
                    var filmModel = data.Films.GetFilmByFilmId(new Random().Next(1, (data.Films.AllFilms().Count() + 1)));
                    if (filmModel == null)
                    {
                        return NotFound();
                    }
                    return RedirectToAction("Index", new { id = filmModel.Id });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"[{DateTime.Now}]\nError: {ex.Message}");
                return NotFound();
            }
        }
    }
}

RandomFilms/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RandomFilms.Data;
using RandomFilms.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RandomFilms.Controllers
{
    [Authorize(Roles = "Editor,Moderator,Admin")]
    [Route("Admin/[controller]/[action]")]
    public class MovieController : Controller
    {
        DataManager data;
        public MovieController(DataManager _data)
        {
            data = _data;
        }
        public IActionResult Index()
        {
            return RedirectToAction("AllFilms");
        }
        #region Film
        [Authorize(Roles = "Editor,Moderator,Admin")]
        public IActionResult AddFilm()
        {
            var countries = data.Country.AllCountries().ToList();
            countries.Sort((x, y) => x.Name.CompareTo(y.Name));
            var genres = data.Generes.AllGenres().ToList();
            genres.Sort((x, y) => x.Genre.CompareTo(y.Genre));
            AddFilmsModel film = new AddFilmsModel
            {
                Countries = countries,
                Geners = genres
            };
            return View(film);
        }
        [HttpPost]
        [Authorize(Roles = "Editor,Moderator,Admin")]
        public IActionResult AddFilm(AddFilmsModel film)
        {
            var countries = data.Country.AllCountries().ToList();
            countries.Sort((x, y) => x.Name.CompareTo(y.Name));
            var genres = data.Generes.AllGenres().ToList();
            genres.Sort((x, y) => x.Genre.CompareTo(y.Genre));
            if (data.Films.CheckFilmByName(film.Films.Name))
            {
                film.Added = 3;
                film.Countries = countries;
                film.Geners = genres;
                return View(film);
            }
            try
            {
                int filmid = data.Films.AllFilms().Count();
                string trailer = film.Films.TrailerURL;
                if (film.Films.TrailerURL.Contains("watch?v="))
                {
                    trailer = trailer.Replace("watch?v=", "embed/");
                }
                FilmModel newFilm = new FilmModel
                {
                    Name = film.Films.Name,
                    FilmGenereModelId = filmid + 1,
                    CountryFilmModelId = filmid + 1,
                    ReleaseDate = DateTime.Parse(film.Films.ReleaseDate).ToLongDateString(),
                    Age = film.Films.Age,
                    Time = film.Films.Time,
                    Description = film.Films.Description,
                    IMDB = film.Films.IMDB,
                    TrailerURL = film.Films.TrailerURL,
                    Image = film.Films.Image,
                    BackGroundImage = film.Films.BackGroundImage,
                };
                data.Films.Save(newFilm);
                for (int i = 0; i < film.GenresSelected.Length; i++)
                {
                    FilmGenersModel model = new FilmGenersModel
                    {
                        Id = default,
                        Gener = data.Generes.GetGenreById(film.GenresSelected[i]).Genre,
                        FilmModelId = filmid + 1
                    };
                    data.FilmGenre.Save(model);
                }
                for (int i = 0; i < film.CountriesSelected.Length; i++)
                {
                    CountryFilmModel model = new CountryFilmModel
                    {
                        Id = default,
                        Country = data.Country.GetCountryById(film.CountriesSelected[i]).Name,
                        FilmModelId = filmid + 1
                    };
                    data.CountryFilm.Save(model);
                }
                AddFilmsModel viewmodel = new AddFilmsModel
                {
                    Countries = countries,
                    Geners = genres,
                    Added = 1

                };
                ModelState.Clear();
                return View(viewmodel);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                AddFilmsModel viewmodel = new AddFilmsModel
                {
                    Countries = countries,
                    Geners = genres,
                    Added = 2
                };
                return View(viewmodel);
            }
        }
        public IActionResult AllFilms()
        {
            return View(data.Films.AllFilms());
        }
        [HttpPost]
        [Authorize(Roles = "Moderator,Admin")]
        public IActionResult Delete(int id)
        {
            data.Films.Delete(id);
            return RedirectToAction("AllFilms");
        }
        #endregion
        [Authorize(Roles = "Moderator,Admin")]
        public IActionResult Edit(int id)
        {
            FilmModel film = data.Films.GetFilmById(id);
            int[] countries = new int[film.Countries.Count()];
            int[] genres = new int[film.Genre.Count()];
            int n = 0;
            if (film == null)
            {
                return NotFound();
            }
            foreach (var item in film.Countries)
            {
                countries[n] = data.Country.GetCountryByName(item.Country).Id;
                n++;
            }
            n = 0;
            foreach (var item in film.Genre)
            {
                genres[n] = data.Generes.GetGenreByString(item.Gener).Id;
                n++;
            }
            EditFilmModel edit = new EditFilmModel
            {
                Id = film.Id,
                Name = film.Name,
                Age = film.Age,
                IMDB = film.IMDB,
                ReleaseDate = DateTime.Parse(film.ReleaseDate),
                Time = film.Time,
                BackGroundImage = film.BackGroundImage,
                Description = film.Description,
                Image = film.Image,
                TrailerURL = film.TrailerURL,
                Geners = data.Generes.AllGenres(),
                Countries = data.Country.AllCountries(),
                CountriesSelected = countries,
                GenresSelected = genres
            };
            return View(edit);
        }
        [HttpPost]
        [Authorize(Roles = "Moderator,Admin")]
        public IActionResult Edit(EditFilmModel edit)
        {
            if (ModelState.IsValid)
            {
                FilmModel model = data.Films.GetFilmById(edit.Id);
                if (model != null)
                {
                    model.Name = edit.Name;
                    model.Age = edit.Age;
                    model.IMDB = edit.IMDB;
                    model.Time = edit.Time;
                    model.ReleaseDate = edit.ReleaseDate.ToLongDateString();
                    model.BackGroundImage = edit.BackGroundImage;
                    model.Description = edit.Description;
                    model.Image = edit.Image;
                    if (edit.TrailerURL.Contains("watch?v="))
                    {
                        edit.TrailerURL = edit.TrailerURL.Replace("watch?v=", "embed/");
                    }
                    model.TrailerURL = edit.TrailerURL;
                    try
                    {
                        data.Films.Save(model);
                        List<string> countryFilms = model.Countries.Select(x => x.Country).ToList();
                        List<string> selectedcoun = new List<string>();
                        for (int i = 0; i < edit.CountriesSelected.Length; i++)
                        {
                            selectedcoun.Add(data.Country.GetCountryById(edit.CountriesSelected[i]).Name);
                        }
                        List<string> rescoun = selectedcoun.Union(countryFilms).Except(countryFilms.Intersect(selectedcoun)).ToList();
                        if (rescoun.Count > 0)
                        {
                            for (int i = 0; i < rescoun.Count(); i++)
                            {
                                if (countryFilms.Contains(rescoun[i]))
                                {
                                    data.CountryFilm.Delete(data.CountryFilm.CountriesByFilmId(model.CountryFilmModelId).FirstOrDefault(x => x.Country == rescoun[i]));
                                }
                                else
                                {
                                    CountryFilmModel newcountry = new CountryFilmModel
                                    {
                                        Id = default,
                                        Country = rescoun[i],
                                        FilmModelId = model.CountryFilmModelId
                                    };
                                    data.CountryFilm.Save(newcountry);
                                }
                            }
                        }
                        List<string> genreFilms = model.Genre.Select(x => x.Gener).ToList();
                        List<string> selectedgenr = new List<string>();
                        for (int i = 0; i < edit.GenresSelected.Length; i++)
                        {
                            selectedgenr.Add(data.Generes.GetGenreById(edit.GenresSelected[i]).Genre);
                        }
                        List<string> resultgenre = selectedgenr.Union(genreFilms).Except(genreFilms.Intersect(selectedgenr)).ToList();
                        if (resultgenre.Count > 0)
                        {
                            for (int i = 0; i < resultgenre.Count(); i++)
                            {
                                if (genreFilms.Contains(resultgenre[i]))
                                {
                                    data.FilmGenre.Delete(data.FilmGenre.GenresById(model.FilmGenereModelId).FirstOrDefault(x => x.Gener == resultgenre[i]));
                                }
                                else

RandomFilms/Views/Movie/AddFilm.cshtml
@model AddFilmsModel
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
    ViewData["Title"] = "Add Film";
}

@if (Model?.Added == 1)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Well done!</strong> Aww yeah, you successfully added film.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
else if (Model?.Added == 2)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> You should check in on some of those fields below.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
else if (Model?.Added == 3)
{
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <i class="fas fa-exclamation-triangle mx-2"></i>
        <div>
            This film has been already added
        </div>
    </div>
}

<div class="card">
    <div class="card-header">
        Add Film
    </div>
    <div class="card-body">
        <form method="post" asp-action="AddFilm" asp-controller="Movie" id="FormEyeDee">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Name</label>
                <input type="text" asp-for="Films.Name" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Country</label><br>
                <select asp-for="@Model.CountriesSelected" name="CountriesSelected" data-width="auto" data-dropup-auto="false" data-size="5" class="selectpicker " data-style="rounded-3 bg-white" data-live-search="true" multiple data-max-options="10" required>
                    @foreach (var item in Model.Countries)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Categories</label><br>
                <select asp-for="@Model.GenresSelected" name="GenresSelected" data-width="auto" data-dropup-auto="false" data-size="5" class="selectpicker " data-style="rounded-3 bg-white" data-live-search="true" multiple data-max-options="10" required>
                    @foreach (var item in Model.Geners)
                    {
                        <option value="@item.Id">@item.Genre</option>
                    }
                </select>
            </div>
            <div class="mb-3 w-100">
                <label for="exampleInputPassword1" class="form-label">Release date</label>
                <input type="date" asp-for="Films.ReleaseDate" min="1900-01-01" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Age</label>
                <input type="number" max="21" asp-for="Films.Age" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Time</label>
                <input type="number" asp-for="Films.Time" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">IMDB</label>
                <input type="number" step="0.01" max="10" min="0" asp-for="Films.IMDB" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Description</label><br>
                <textarea class="form-control" asp-for="Films.Description" required></textarea>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Image</label>
                <input type="text" asp-for="Films.Image" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Background Image</label>
                <input type="text" asp-for="Films.BackGroundImage" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Trailer</label>
                <input type="text" asp-for="Films.TrailerURL" class="form-control" required>
            </div>
            <div asp-validation-summary="ModelOnly"></div>
            <input type="submit" class="btn btn-primary" value="Add Film">
            <input type="submit" class="btn btn-primary" asp-action="Preview" value="Preview">
        </form>
    </div>
</div>

RandomFilms/Views/Movie/AllFilms.cshtml
@model IEnumerable<FilmModel>
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
    ViewData["Title"] = "Films";
}
<div class="card">
    <div class="card-header">
        All Films
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="example" class="table  table-borderless">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Country</th>
                        <th>Date</th>
                        <th>Age</th>
                        <th>Time</th>
                        <th>IMDB</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td><a asp-action="Index" asp-controller="Film" asp-route-id="@item.Id">@item.Name</a> </td>
                            <td>@string.Join(", ", item.Countries.Select(x=>x.Country))</td>
                            <td>@item.ReleaseDate</td>
                            <td>@item.Age</td>
                            <td>@item.Time</td>
                            <td>@item.IMDB</td>
                            <td class="d-flex" align="center">
                                <a class="btn btn-link mx-2" asp-action="Edit" asp-route-id="@item.Id"> <i class="fas fa-pencil-alt"></i></a>
                                <form asp-action="Delete" asp-route-id="@item.Id" class="d-flex align-content-center" method="post">
                                    <button type="submit" class="btn btn-link mx-2"> <i class="fas fa-trash"></i></button>
                                </form>

                            </td>
                        </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Country</th>
                        <th>Date</th>
                        <th>Age</th>
                        <th>Time</th>
                        <th>IMDB</th>
                        <th>Action</th>
                    </tr>
                </tfoot>

            </table>
        </div>
    </div>
</div>

RandomFilms/Views/Movie/Edit.cshtml
@model EditFilmModel
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
    ViewData["Title"] = "Edit Film";
    int n = 0;
}
@if (Model?.State == 1)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Well done!</strong> Aww yeah, you successfully edited film.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
else if (Model?.State == 2)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> You should check in on some of those fields below.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="card">
    <div class="card-header">
        Edit Film
    </div>
    <div class="card-body">
        <form method="post" asp-action="Edit" asp-controller="Movie">
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Name</label>
                <input type="text" asp-for="Name" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Country</label><br>
                <select asp-for="@Model.CountriesSelected" name="CountriesSelected" data-width="auto" data-dropup-auto="false" data-size="5" class="selectpicker " data-style="rounded-3 bg-white" data-live-search="true" multiple data-max-options="10" required>
                    @foreach (var item in Model.Countries)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Categories</label><br>
                <select asp-for="@Model.GenresSelected" name="GenresSelected" data-width="auto" data-dropup-auto="false" data-size="5" class="selectpicker " data-style="rounded-3 bg-white" data-live-search="true" multiple data-max-options="10" required>
                    @foreach (var item in Model.Geners)
                    {
                        <option value="@item.Id">@item.Genre</option>
                    }
                </select>
            </div>
            <div class="mb-3 w-100">
                <label for="exampleInputPassword1" class="form-label">Release date</label>
                <input type="date" asp-for="ReleaseDate" min="1900-01-01" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Age</label>
                <input type="number" max="21" asp-for="Age" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Time</label>
                <input type="number" asp-for="Time" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">IMDB</label>
                <input type="number" step="0.01" max="10" min="0" asp-for="IMDB" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Description</label><br>
                <textarea class="form-control" asp-for="Description" required></textarea>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Image</label>
                <input type="text" asp-for="Image" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Background Image</label>
                <input type="text" asp-for="BackGroundImage" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Trailer</label>
                <input type="text" asp-for="TrailerURL" class="form-control" required>
            </div>
            <div asp-validation-summary="All"></div>
            <input type="submit" class="btn btn-primary" value="Save">
        </form>
    </div>
</div>