RandomFilms/Controllers/GenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RandomFilms.Data;
using RandomFilms.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RandomFilms.Controllers
{
    [Authorize(Roles = "Editor,Moderator,Admin")]
    [Route("Admin/[controller]/[action]")]
    public class GenreController : Controller
    {
        DataManager data;
        public GenreController(DataManager _data)
        {
            data = _data;
        }
        public IActionResult Index()
        {
            return RedirectToAction("AllGenres");
        }
        [HttpGet]
        [Authorize(Roles = "Moderator,Admin")]
        public IActionResult AddGenre()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Moderator,Admin")]
        public IActionResult AddGenre(GenreModel genres)
        {
            if (data.Generes.CheckGenreByName(genres.Genre))
            {
                GenreModel gen = new GenreModel
                {
                    Id = 2
                };
                return View(gen);
            }
            data.Generes.Save(genres);
            GenreModel g = new GenreModel
            {
                Id = 1
            };
            return View(g);
        }
        public IActionResult AllGenres()
        {
            List<FilmGenreTable> table = new List<FilmGenreTable>();
            List<GenreModel> model = data.Generes.AllGenres().ToList();
            model.Sort((x, y) => x.Genre.CompareTo(y.Genre));
            foreach (var item in model)
            {
                int count = data.FilmGenre.CountFilmGenre(item.Genre);
                FilmGenreTable film = new FilmGenreTable
                {
                    Genre = item.Genre,
                    Count = count
                };
                table.Add(film);
            }
            return View(table);
        }
        [HttpPost]
        [Authorize(Roles = "Moderator,Admin")]
        public IActionResult Delete(int id)
        {
            GenreModel genre = data.Generes.GetGenreById(id);
            if (genre != null)
            {
                data.Generes.Delete(genre);
            }
            return RedirectToAction("AllGenres");
        }
    }
}

RandomFilms/Views/Genre/AddGenre.cshtml
@model GenreModel
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
    ViewData["Title"] = "Add Genre";
}
@if (Model?.Id == 1)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Well done!</strong> Aww yeah, you successfully added genre.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
else if (Model?.Id == 2)
{
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <i class="fas fa-exclamation-triangle mx-2"></i>
        <div>
            This genre has been already added
        </div>
    </div>
}
<div class="card">
    <h5 class="card-header">Add Genre</h5>
    <div class="card-body">
        <form asp-controller="Genre" asp-action="AddGenre" method="post">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Genre</label>
                <input type="text" class="form-control" asp-for="Genre" placeholder="Genre" required>
            </div>
            <div asp-validation-summary="ModelOnly"></div>
            <input type="submit" class="btn btn-primary" value="Add Genre">
        </form>
    </div>
</div>

RandomFilms/Views/Genre/AllGenres.cshtml
@model List<FilmGenreTable>
@{
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
    ViewData["Title"] = "Genres";
}
<div class="card">
    <h5 class="card-header">All Genres</h5>
    <div class="card-body">
        <div class="table-responsive">
            <table id="example" class="table  table-borderless">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Count</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Genre</td>
                            <td>@item.Count</td>
                            <td>
                                <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                                    <button type="submit" class="btn btn-link">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }


                </tbody>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Count</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>